--general
E2Helper.Descriptions["aceIsEngine"] = "Returns 1 if the entity is an ACE engine."
E2Helper.Descriptions["aceIsGearbox"] = "Returns 1 if the entity is an ACE gearbox."
E2Helper.Descriptions["aceIsGun"] = "Returns 1 if the entity is an ACE gun."
E2Helper.Descriptions["aceIsRack"] = "Returns 1 if the entity is an ACE rack."
E2Helper.Descriptions["aceIsAmmo"] = "Returns 1 if the entity is an ACE ammo crate."
E2Helper.Descriptions["aceIsFuel"] = "Returns 1 if the entity is an ACE fuel tank."
E2Helper.Descriptions["aceIsRadar"] = "Returns 1 if the entity is an ACE radar."
E2Helper.Descriptions["aceActive(e:)"] = "Returns whether an ACE engine, ammo crate, or fuel tank is active."
E2Helper.Descriptions["aceActive(e:n)"] = "Sets whether an ACE engine, ammo crate, or fuel tank is active."
E2Helper.Descriptions["aceHitClip"] = "Returns 1 if hitpos is on a clipped part of prop."
E2Helper.Descriptions["aceNameShort"] = "Returns the short name of an ACE entity."
E2Helper.Descriptions["aceName"] = "Returns the full name of an ACE entity."
E2Helper.Descriptions["aceType"] = "Returns the type of ACE entity."
E2Helper.Descriptions["aceLinkTo"] = "Link various ACE components together."
E2Helper.Descriptions["aceUnlinkFrom"] = "Unlink various ACE components."
E2Helper.Descriptions["aceCapacity"] = "Returns the capacity of an ACE ammo crate or fuel tank."
E2Helper.Descriptions["aceInfoRestricted"] = "Returns 1 if functions returning sensitive info are restricted to owned and friends props."
E2Helper.Descriptions["aceLinks"] = "Returns all entities which are linked to this entity through ACE."
E2Helper.Descriptions["aceGetLinkedWheels"] = "Returns any wheels linked to this engine/gearbox or its children links."
E2Helper.Descriptions["aceDragDiv"] = "Returns the current ACE drag divisor."
E2Helper.Descriptions["aceHeat"] = "Returns the temperature of an ACE entity."
E2Helper.Descriptions["aceVersion"] = "Returns latest git version of ACE."
E2Helper.Descriptions["aceCurVersion"] = "Returns current version of ACE."
E2Helper.Descriptions["aceHEATAirGapFactor"] = "Returns the current air gap factor (air effectiveness against HEAT). Its value represents the percentage of energy remaining after 1 meter of travel."
E2Helper.Descriptions["aceWindVector"] = "Returns the current ACE wind direction vector."
--engine
E2Helper.Descriptions["aceMaxTorque"] = "Returns the peak torque of an ACE engine, in Nm."
E2Helper.Descriptions["aceMaxPower"] = "Returns the peak power of an ACE engine, in kW."
E2Helper.Descriptions["aceMaxTorqueWithFuel"] = "Returns the peak torque of an ACE engine with fuel linked, in Nm."
E2Helper.Descriptions["aceMaxPowerWithFuel"] = "Returns the peak power of an ACE engine with fuel linked, in kW."
E2Helper.Descriptions["aceIdleRPM"] = "Returns the idle RPM of an ACE engine."
E2Helper.Descriptions["acePowerbandMin"] = "Returns the lower powerband of an ACE engine."
E2Helper.Descriptions["acePowerbandMax"] = "Returns the upper powerband of an ACE engine."
E2Helper.Descriptions["aceRedline"] = "Returns the redline RPM of an ACE engine."
E2Helper.Descriptions["aceRPM"] = "Returns the current RPM of an ACE engine."
E2Helper.Descriptions["aceTorque"] = "Returns the current torque of an ACE engine, in Nm."
E2Helper.Descriptions["aceFlyInertia"] = "Returns the inertia of an ACE engine's flywheel."
E2Helper.Descriptions["aceFlyMass"] = "Returns the mass of an ACE engine's flywheel."
E2Helper.Descriptions["acePower"] = "Returns the current power of an ACE engine, in kW."
E2Helper.Descriptions["aceInPowerband"] = "Returns 1 if an ACE engine's RPM is within the powerband."
E2Helper.Descriptions["aceThrottle(e:)"] = "Gets throttle (0-100) for an ACE engine."
E2Helper.Descriptions["aceThrottle(e:n)"] = "Sets throttle (0-100) for an ACE engine."
E2Helper.Descriptions["aceFuelRemaining"] = "Returns the amount of fuel remaining for an ACE engine, in litres or kilowatt-hours."
E2Helper.Descriptions["aceGetFuelTanks"] = "Returns an array of all fuel tanks linked to an ACE engine."
E2Helper.Descriptions["aceIsElectric"] = "Returns 1 if an ACE engine is electric."

--gearbox
E2Helper.Descriptions["aceGear"] = "Returns the current gear of an ACE gearbox."
E2Helper.Descriptions["aceNumGears"] = "Returns the number of gears of an ACE gearbox."
E2Helper.Descriptions["aceFinalRatio"] = "Returns the final ratio of an ACE gearbox."
E2Helper.Descriptions["aceTorqueRating"] = "Returns the maximum torque that an ACE gearbox can handle, in Nm."
E2Helper.Descriptions["aceIsDual"] = "Returns 1 if an ACE gearbox is dual clutch."
E2Helper.Descriptions["aceShiftTime"] = "Returns the time an ACE gearbox takes to change gears, in ms."
E2Helper.Descriptions["aceInGear"] = "Returns 1 if an ACE gearbox is in gear."
E2Helper.Descriptions["aceTotalRatio"] = "Returns the total ratio (current gear * final) of an ACE gearbox."
E2Helper.Descriptions["aceGearRatio"] = "Returns the ratio of a specified gear of an ACE gearbox."
E2Helper.Descriptions["aceTorqueOut"] = "Returns the current torque output an ACE gearbox, in Nm."
E2Helper.Descriptions["aceCVTRatio"] = "Sets the gear ratio of a CVT. Set to 0 to enable automatic ratio control."
E2Helper.Descriptions["aceShift"] = "Shift to the specified gear for an ACE gearbox."
E2Helper.Descriptions["aceShiftUp"] = "Shifts an ACE gearbox up."
E2Helper.Descriptions["aceShiftDown"] = "Shifts an ACE gearbox down."
E2Helper.Descriptions["aceBrake"] = "Sets the brake for an ACE gearbox. Sets both sides of a dual clutch gearbox."
E2Helper.Descriptions["aceBrakeLeft"] = "Sets the left brake for an ACE gearbox. Only works for dual clutch."
E2Helper.Descriptions["aceBrakeRight"] = "Sets the right brake for an ACE gearbox. Only works for dual clutch."
E2Helper.Descriptions["aceClutch"] = "Sets the clutch for an ACE gearbox. Sets both sides of a dual clutch gearbox."
E2Helper.Descriptions["aceClutchLeft"] = "Sets the left clutch for an ACE gearbox. Only works for dual clutch."
E2Helper.Descriptions["aceClutchRight"] = "Sets the right clutch for an ACE gearbox. Only works for dual clutch."
E2Helper.Descriptions["aceSteerRate"] = "Sets the steer ratio for an ACE double differential gearbox."
E2Helper.Descriptions["aceHoldGear"] = "Set to 1 to stop ACE automatic gearboxes upshifting."
E2Helper.Descriptions["aceShiftPointScale"] = "Sets the shift point scale for an ACE automatic gearbox."

--guns
E2Helper.Descriptions["aceIsReloading"] = "Returns 1 if an ACE weapon is reloading."
E2Helper.Descriptions["aceReady"] = "Returns 1 if an ACE weapon is ready to fire."
E2Helper.Descriptions["aceMagSize"] = "Returns the magazine capacity of an ACE weapon."
E2Helper.Descriptions["aceMagReloadTime"] = "Returns time it takes for an ACE weapon to reload magazine."
E2Helper.Descriptions["aceReloadTime"] = "Returns time to next shot of an ACE weapon."
E2Helper.Descriptions["aceReloadProgress"] = "Returns number between 0 and 1 which represents reloading progress of an ACE weapon. Useful for progress bars."
E2Helper.Descriptions["aceSpread"] = "Returns the spread of an ACE weapon."
E2Helper.Descriptions["aceFireRate"] = "Returns the rate of fire of an ACE weapon."
E2Helper.Descriptions["aceSetROFLimit"] = "Sets the rate of fire limit of an ACE weapon."
E2Helper.Descriptions["aceFire"] = "Sets the firing state of an ACE weapon.  Kills are only attributed to gun owner.  Use wire inputs on gun if you want to properly attribute kills to driver."
E2Helper.Descriptions["aceUnload"] = "Causes an ACE weapon to unload."
E2Helper.Descriptions["aceReload"] = "Causes an ACE weapon to reload."
E2Helper.Descriptions["aceMagRounds"] = "Returns the rounds remaining in the magazine of an ACE weapon."
E2Helper.Descriptions["aceMunitions"] = "Returns the number of rounds of an ACE Ammo Crate."
E2Helper.Descriptions["aceAmmoCount"] = "Returns the number of rounds in active ammo crates linked to an ACE weapon."
E2Helper.Descriptions["aceTotalAmmoCount"] = "Returns the number of rounds in all ammo crates linked to an ACE weapon."
E2Helper.Descriptions["aceGetCrew"] = "Returns a list of all the crew seats of an ACE Entity."
E2Helper.Descriptions["aceGetAmmoCrates"] = "Returns a list of all the ammo crates of an ACE Weapon."
E2Helper.Descriptions["aceState"] = "Returns the state of an ACE weapon."

--ammo
E2Helper.Descriptions["aceRounds"] = "Returns the number of rounds in an ACE ammo crate."
E2Helper.Descriptions["aceAmmoType"] = "Returns the type of ammo in an ACE ammo crate or ACE weapon."
E2Helper.Descriptions["aceRoundType"] = "Returns the type of weapon the ammo in an ACE ammo crate loads into."
E2Helper.Descriptions["aceCaliber"] = "Returns the caliber of the weapon or ammo."
E2Helper.Descriptions["aceMuzzleVel"] = "Returns the muzzle velocity of the ammo in an ACE ammo crate or weapon."
E2Helper.Descriptions["aceProjectileMass"] = "Returns the mass of the projectile in an ACE ammo crate or weapon."
E2Helper.Descriptions["aceFLSpikes"] = "Returns the number of projectiles in a flechette round."
E2Helper.Descriptions["aceFLSpikeRadius"] = "Returns the radius (in mm) of the spikes in a flechette round."
E2Helper.Descriptions["aceFLSpikeMass"] = "Returns the mass of a single spike in a FL round in a crate or gun."
E2Helper.Descriptions["acePenetration(e:)"] = "Returns the penetration of a round in an ACE ammo crate or gun."
E2Helper.Descriptions["acePenetration(e:n)"] = "Returns the penetration of a round in an ACE ammo crate or gun, with an index to check penetration for THEAT (uses indexes 1 and 2)."
E2Helper.Descriptions["aceBlastRadius"] = "Returns the blast radius of an HE, APHE, or HEAT round in an ACE ammo crate or weapon."
E2Helper.Descriptions["aceDragCoef"] = "Returns the drag coefficient of ammo in an ACE ammo crate or weapon."

--armor
E2Helper.Descriptions["acePropHealth"] = "Returns the current health of an entity."
E2Helper.Descriptions["acePropHealthMax"] = "Returns the max health of an entity."
E2Helper.Descriptions["acePropArmor"] = "Returns the current armor of an entity."
E2Helper.Descriptions["acePropArmorMax"] = "Returns the max armor of an entity."
E2Helper.Descriptions["acePropDuctility"] = "Returns the ductility of an entity."
E2Helper.Descriptions["aceEffectiveArmor"] = "Returns the effective armor of a given nominal armor value and angle, or from a trace hitting an entity."
E2Helper.Descriptions["acePropMaterial"] = "Returns the material of an entity."
E2Helper.Descriptions["acePropArmorData"] = "Returns a table with armor data of the prop. Keys:\nCurve = [N]\nEffectiveness = [N]\nHEATEffectiveness = [N]\nMaterial = [S]"

--fuel
E2Helper.Descriptions["aceFuel"] = "Returns the remaining liters of fuel or kilowatt hours in an ACE fuel tank, or available to an engine."
E2Helper.Descriptions["aceFuelLevel"] = "Returns the percent remaining fuel in an ACE fuel tank, or available to an engine."
E2Helper.Descriptions["aceFuelRequired"] = "Returns 1 if an ACE engine requires fuel."
E2Helper.Descriptions["aceRefuelDuty"] = "Sets an ACE fuel tank on refuel duty, causing it to supply other fuel tanks with fuel."
E2Helper.Descriptions["aceFuelUse"] = "Returns the current fuel consumption of an engine in liters per minute or kilowatts."
E2Helper.Descriptions["acePeakFuelUse"] = "Returns the peak fuel consumption of an engine in liters per minute or kilowatts."

--radars
E2Helper.Descriptions["aceRadarData"] = "Returns a table containing the outputs you'd get from an ACE tracking radar, missile radar, or IRST.\nCheck radar wire outputs for key names."